import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navBar";
import { ThemeProvider } from "../components/themeProvider";
import { Space_Grotesk } from "next/font/google";
import StarryNight from "@/components/starryNight";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Ben Chamberlain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={spaceGrotesk.variable}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StarryNight />
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
